apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: my-ap-policy
  namespace: default
spec:
  policy:
    name: my-ap-policy
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    server-technologies:
      - serverTechnologyName: Unix/Linux
      - serverTechnologyName: Nginx
      - serverTechnologyName: "Apache/NCSA HTTP Server"
      - serverTechnologyName: PHP
      - serverTechnologyName: JavaScript
      - serverTechnologyName: PostgreSQL
    signature-requirements:
    - tag: Fruits
    signature-sets:
    - name: apple_sigs
      block: true
      signatureSet:
        filter:
          tagValue: Fruits
          tagFilter: eq
    bot-defense:
      settings:
        isEnabled: true
      mitigations:
        classes:
        - name: trusted-bot
          action: alarm
        - name: untrusted-bot
          action: alarm
        - name: malicious-bot
          action: block
