apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: my-waf-policy
  namespace: default
spec:
  waf:
    enable: true
    apPolicy: "default/my-ap-policy"
    securityLogs:
    - enable: true
      apLogConf: "default/logconf"
#     logDest: "syslog:server=syslog-svc.default:514"
      logDest: "syslog:server=ec2-54-82-92-107.compute-1.amazonaws.com:515"
#      logDest: "stderr"
